services:

  haraka:
    build:
      context: .
      dockerfile: Dockerfile

    restart: always

    volumes:
      - haraka_data:/haraka

    command: >
      sh -c "
      if [ ! -d /haraka/config ]; then
        /usr/local/bin/haraka -i /haraka
      fi &&
      /usr/local/bin/haraka -c /haraka
      "

volumes:
  haraka_data:
